---
configs:

    use: 'centos'
    ubuntu:
        box: 'ubuntu/xenial64'
        box_version: '20211001.0.0'
        playbook: 'playbook-ubuntu.yml'
        public_ip: '192.168.0.117'
#        <more variables>...

    centos:
        box: 'centos/7'
        box_version: '2004.01'
        playbook: 'playbook-centos.yml'
        public_ip: '192.168.0.120'
#        <more variables>...

