---
- hosts: all
  become: true
  vars_files:
    - vars/default.yml

  tasks:

    - name: Copy files from local host to remote host
      copy:
        src: "./webapp/"
        dest: "/var/www/{{ http_host }}/wordpress"
        owner: apache
        group: apache
        mode: '0640'
        force: true

    - name: Restart Apache
      service:
        name: httpd
        state: restarted
